<?php
/**
 * Plugin Name: WPSustainable
 * Description: Check the sustainability from your hosting company and the CO2 generated by your IP address.
 * Requires at least: 5.2
 * Requires PHP: 7.0
 * Version: 1.1.0
 * Author: Sustainability Team Contributors
 * Text Domain: wpsustainable
 * Domain Path: /languages
 * License: GPL 2.0
 * License URI: https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * @package WPSustainable
 *
 * @version 1.1.0
 */

/**
 * If this file is called directly, abort.
 */
defined( 'ABSPATH' ) || die( 'Sorry!' );

/**
 * URL of the plugin
 */
define( 'WPSUSTAINABLE_PLUGIN_URL', plugins_url( '/', __FILE__ ) );

/**
 * Version of the plugin
 */
define( 'WPSUSTAINABLE_PLUGIN_VERSION', '1.1.0' );

/**
 * The main plugin file
 */
define( 'WPSUSTAINABLE_PLUGIN_FILE', __FILE__ );

/**
 * Basename of the plugin
 */
define( 'WPSUSTAINABLE_PLUGIN_BASE', plugin_basename( __FILE__ ) );

/**
 * Absolute path to the directory of the plugin
 */
define( 'WPSUSTAINABLE_PLUGIN_PATH', plugin_dir_path( __FILE__ ) );

/**
 * Initializes the plugin after all plugins have loaded.
 *
 * This function loads the plugin textdomain for internationalization.
 *
 * @since 1.1.0
 */
function wpsustainable_plugin_init() {
	load_plugin_textdomain( 'wpsustainable', false, dirname( plugin_basename( __FILE__ ) ) . '/languages' );
}
add_action( 'plugins_loaded', 'wpsustainable_plugin_init' );

/**
 * Include the helper functions for the API.
 */
require_once WPSUSTAINABLE_PLUGIN_PATH . '/includes/helper-sustainable-api.php';

/**
 * Include the class for managing health checks.
 */
require_once WPSUSTAINABLE_PLUGIN_PATH . '/includes/class-sustainable-health.php';

/**
 * Include the class for managing badges.
 */
require_once WPSUSTAINABLE_PLUGIN_PATH . '/badge/class-sustainable-badge.php';
